// --- Generated by Signaloid CLI ---

// Type definitions for the inputs that will be used in the Angular application.
export type InputType = 'text' | 'basic-slider' | 'distribution-slider' | 'multiple-choice' | 'file';

export interface BaseInputConfig {
	id: string;
	name: string;
	argumentFlag: string;
	type: InputType;
}

export interface TextInputConfig extends BaseInputConfig {
	type: 'text';
	initialValue: string;
}

export interface SliderConfig extends BaseInputConfig {
	type: 'basic-slider' | 'distribution-slider';
	min: number;
	max: number;
	step: number;
	initialValue: number;
	xAxisLabel: string;
	adjustWidth: boolean;
	isDistribution: boolean;
	initialDistribution?: [number, number][];
}

export interface MultipleChoiceConfig extends BaseInputConfig {
	type: 'multiple-choice';
	options: { name: string; value: string }[];
	initialValue: string;
}

export interface FileInputConfig extends BaseInputConfig {
	type: 'file';
	accept: string;
	destination: string;
}

export type InputConfig = TextInputConfig | SliderConfig | MultipleChoiceConfig | FileInputConfig;

// The array of configured inputs, generated based on user prompts.
export const demoInputs: InputConfig[] = [
	{
		id: 'temperature',
		name: 'Temperature (ADC Reading)',
		xAxisLabel: 'Temperature (ADC Reading)',
		argumentFlag: ' -t ',
		adjustWidth: false,
		type: 'distribution-slider',
		min: 250000,
		max: 700000,
		step: 25000,
		initialValue: 525000,
		isDistribution: true,
		initialDistribution: [
			[500000, 75],
			[525000, 75],
			[550000, 75],
		],
	},
	{
		id: 'pressure',
		name: 'Pressure (ADC Reading)',
		xAxisLabel: 'Pressure (ADC Reading)',
		argumentFlag: ' -p ',
		adjustWidth: false,
		type: 'distribution-slider',
		min: 200000,
		max: 800000,
		step: 25000,
		initialValue: 300000,
		isDistribution: true,
		initialDistribution: [
			[275000, 75],
			[300000, 75],
			[325000, 75],
		],
	},
	{
		id: 'humidity',
		name: 'Humidity (ADC Reading)',
		xAxisLabel: 'Humidity (ADC Reading)',
		argumentFlag: ' -u ',
		adjustWidth: false,
		type: 'distribution-slider',
		min: 12000,
		max: 30000,
		step: 1000,
		initialValue: 15000,
		isDistribution: true,
		initialDistribution: [
			[14000, 75],
			[15000, 75],
			[16000, 75],
		],
	},
];
